# Ansible Inventory - Target Nodes for Web Server Deployment

[webservers]
web_node_1 ansible_host=target_node_1 ansible_connection=docker ansible_user=root
web_node_2 ansible_host=target_node_2 ansible_connection=docker ansible_user=root

[all:vars]
ansible_python_interpreter=/usr/bin/python3
web_port=80
site_title="DevOps Lab 3 - Automated Web Server"
